### PR TITLE
Travis to GitHub

### PR DESCRIPTION
**Pull request by pberkes**
Switch CI from TravisCI to Github actions

### CODE REVIEW

**Comment by pberkes** [comment]
@Debilski 
I've seen that you did, but I'm trying to have a way for the students to have a feedback while they are experimenting with creating a workflow, so I tried this strategy. In this way, every time you push the branch you can see if it's working or not.

Another option would be for them to create a PR immediately after the first commit, but sadly they would need to create a fake PR to their fork because workorders do not execute for PRs from forks for first-time committers, they need to be manually authorized first.

Do you know of some other way of achieving this?

**Comment by Debilski** [comment]
Good point. I hadn’t thought about that, yeah, makes sense to keep it then.

There are a few ideas in here https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/6 but most are far too complicated or won’t really help for this use case. I’m actually not sure if the two actions run on the same code or if the PR action runs on the merged version of the code.

This one
    on:
      push:
      pull_request:
        types: [opened]

would at least stop it from running the action twice when commits are added to a PR (but would still run it twice initially). But this can also be confusing, so I’m not really sure what to do here.

**Comment by pberkes** [comment]
No the SHA associated with the pull-request trigger is still the one on the branch.

The workflow is executed at least 3 times: 1) when you push the branch; 2) when you open the PR; 3) when the PR is merged and pushed to master.

The third case is useful because there might be some changes in master that break the PR code (it happened to me in the past)

**Comment by Debilski** [comment]
Yeah, the 3rd case is definitely sensible. (Only annoying when there is a random failure in it.)

**Comment by pberkes** [comment]
The problem is only relevant when modifying the github actions jobs themselves.

One possible workflow could be:
- create an actions file with `on: push`
- develop and debug on the branch by pushing regularly
- when it works properly, do a commit changing the triggers to
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```
- open a pull request against the main repo
- the owner of the main fork will have to authorize at this point but it should work

@Debilski @lschwetlick  what do you think?

**Comment by Debilski** [comment]
One thing to note: I doubt that the students ‘in real life’ will spend too much time opening pull requests. As far as I see it in our own GitLab instance, everyone is just pushing to master or people use their own branch and then freak out regularly when the branch has diverted too much. At that point, a pull request is worthless because the merge has to be made manually anyway.

So, it is probably better to tell the students that they should just put both `push:` and `pull_requests:` in there for their own projects, without restrictions, and then the CI runs twice (in the rare case of a PR) but whatever.
If you have a public project with restricted access, then things are different and you might wish to clean it up but that’s more of a bonus.

**Pull request merged**
